### ISSUE TITLE
Project Management Documentation

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#1]
## Summary

Sort of a meta issue but we need to draft, refine, and document our approach to project management as we develop this course. Note that we have extensive documentation in our Shared Google Drive but much of that is only intended for internal use. GitHub is the intuitive choice for task management because of the nature of the course content and because we can directly connect tasks (i.e., issues) to the relevant source components of the course website.

## Sub-Tasks

- [x] Draft project management system
- [x] Draft project management documentation
- [x] Ping Marty for review
- [ ] Refine system and/or documentation as needed

## Resources

- SSECR GitHub repo's [CONTRIBUTING.md](https://github.com/lter/ssecr/blob/main/CONTRIBUTING.md)

**Comment by njlyon0** [comment]
## Progress Update

Made substantial headway in drafting a project management system (this was--in some ways--prerequisite to being able to open this issue in the first place). Need to officially document it but here are the highlights:

- Use issues for tracking [S.M.A.R.T.](https://en.wikipedia.org/wiki/SMART_criteria) tasks
    - Issues should use the 'Task Template'
    - Issues should be assigned to a person, given an appropriate label, and added to the [SSECR Course Tasks](https://github.com/orgs/lter/projects/6) GitHub Project
- GitHub Project
   - For strategic planning, issue lifecycle should be tracked in the [SSECR Course Tasks](https://github.com/orgs/lter/projects/6) GitHub Project
   - Allows for easier 'situation report' of all extant tasks than scrolling through the repo's "Issues" tab would allow
   - Likely needed categories (in Project) predicted and added (incl: "Back Burner, Active Progress", "Pending Feedback (Internal)", "Pending Feedback (External)", and "Done")
- Accessing course repo
    - [ssecr](https://github.com/orgs/lter/teams/ssecr) GitHub team has _Write-level access_ to Project & repository
    - Can add users individually to Project/repo if higher level access is needed

### Next Sub-Task(s)

- [ ] Document above summary in an easily findable location
    - Consider appropriate level of detail

**Comment by njlyon0** [comment]
## Wrote Documentation - 1^st Draft

Decided to take the first pass at project documentation in [CONTRIBUTING.md](https://github.com/lter/ssecr/blob/main/CONTRIBUTING.md) so that it is readily accessible to anyone working in the GitHub repo (hopefully). Need to send over to Marty for feedback but feel reasonably good about this draft

**Comment by njlyon0** [comment]
## Done (for now)

Marty gave me the green light for now. We may / likely will return and revise once we get a sense for where more / different documentation would be valuable but that won't be until we have more people actively contributing
