### ISSUE TITLE
Draft Bonus Module: 'Spatial Data'

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#10]
## Summary

Need to create a strong draft of this module so that we can revise and eventually offer this section of the course.

## Sub-Tasks

- [x] Draft module skeleton
- [x] Draft learning objectives
    - Consider using a diversity of [Bloom's Revised Taxonomy](https://www.celt.iastate.edu/instructional-strategies/effective-teaching-practices/revised-blooms-taxonomy/) verbs
- [x] Draft content
    - Could include, text, code, slides, or some combination of those!
- ~~Identify companion readings / activities~~
    - None for this module because it's a "bonus" one (rather than one we're covering synchronously)
- [x] Identify bonus resources
    - "Bonus" as in related but external resources that are not a required part of the module but might be useful for students interested in delving deeper
- [ ] Gather feedback from SSECR design team
    - [ ] Implement feedback

## Resources

- SSECR website [module page](https://lter.github.io/ssecr/mod_spatial.html)
- "Draft Course Objectives" Google Doc
    - In Shared Drive for course
- Arctic Data Center ["Working with Spatial Data" Training](https://learning.nceas.ucsb.edu/2024-02-arctic/session_19.html) 
- Rachel King's ["Spatial Data Visualization" lesson GitHub repo](https://github.com/king0708/spatial-data-viz)

**Comment by njlyon0** [comment]
## Significant Progress!

Fleshed out a reasonably strong draft of the first few topics of this module. That includes the 'data types' topic (vector vs. raster) as well as the CRS topic (checking / transforming CRS). Next up is map-making!

**Comment by njlyon0** [comment]
## First Draft Complete

Finished the first draft of this module! Could use another set of eyes (i.e., some feedback/revision) but calling the _first_ draft 'done' here

**Comment by njlyon0** [comment]
## Done

This module has been fleshed out since July (~3 months) without feedback. The fact that it's a bonus module in combination with this means I'm closing this issue. Will open a related 'improvements' issue if/when people have feedback here.

Still valuable to close this just to tidy up the GitHub project/issues space
