### ISSUE TITLE
Draft 'Reproducible Reports' Module

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#11]
## Summary

Need to create a strong draft of this module so that we can revise and eventually offer this section of the course.

## Sub-Tasks

- [ ] Draft module skeleton
- [ ] Draft learning objectives
    - Consider using a diversity of [Bloom's Revised Taxonomy](https://www.celt.iastate.edu/instructional-strategies/effective-teaching-practices/revised-blooms-taxonomy/) verbs
- [ ] Discuss with SSECR development team
    - [ ] Refine skeleton / learning objectives as needed
- [ ] Draft content
    - Could include, text, code, slides, or some combination of those!
- [ ] Identify companion readings / activities
    - For readings, may make sense to divide between readings for before and readings for after
- [ ] Identify bonus resources
    - "Bonus" as in related but external resources that are not a required part of the module but might be useful for students interested in delving deeper
- [ ] Gather feedback from SSECR design team
    - [ ] Implement feedback

## Resources

- SSECR website [module page](https://lter.github.io/ssecr/mod_reports.html)
- "Draft Course Objectives" Google Doc
    - In Shared Drive for course

## Resources

- TBD

**Comment by njlyon0** [comment]
## Progress!

Finished the draft of the fundamental structure topic. Covered the general purpose of notebook files as well as the three fundamental bits of a notebook file (YAML, markdown text, code chunks).

Planning on fleshing out a small 'notebook vs. script' aside then moving on to an 'applications' topic and ending on a 'deployment/GitHub Actions' topic

**Comment by njlyon0** [comment]
## Update

Not finished with this module (or finished enough to request feedback formally) but made some great progress!

I think the new module order should be:

1. Fundamentals of Notebooks
2. Tutorial on making a Quarto website
    - Activity: making an individual website (one member per group could make the team website instead) 
3. Customizing a website with SCSS
   - Activity: customizing the website from the prior activity

## Work Still to be Done

Need to do the following:

- [ ] Decide whether to discuss GitHub Actions (remove from learning obj.s if not covering)
- [ ] Flesh out customizing website component
- [ ] Work through tutorial to see if meets all desired needs
- [ ] Generally review all materials to make sure organization / flow works
