### ISSUE TITLE
Draft 'Team Science Practices' Module

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#12]
## Summary

Need to create a strong draft of this module so that we can revise and eventually offer this section of the course.

## Sub-Tasks

- [ ] Draft module skeleton
- [ ] Draft learning objectives
    - Consider using a diversity of [Bloom's Revised Taxonomy](https://www.celt.iastate.edu/instructional-strategies/effective-teaching-practices/revised-blooms-taxonomy/) verbs
- [ ] Discuss with SSECR development team
    - [ ] Refine skeleton / learning objectives as needed
- [ ] Draft content
    - Could include, text, code, slides, or some combination of those!
- [ ] Identify companion readings / activities
    - For readings, may make sense to divide between readings for before and readings for after
- [ ] Identify bonus resources
    - "Bonus" as in related but external resources that are not a required part of the module but might be useful for students interested in delving deeper
- [ ] Gather feedback from SSECR design team
    - [ ] Implement feedback

## Resources

- SSECR website [module page](https://lter.github.io/ssecr/mod_team-sci.html)
- "Draft Course Objectives" Google Doc
    - In Shared Drive for course

**Comment by njlyon0** [comment]
@ckappel & @marty-downs , the module is looking great! I've opened an issue for teaching this module (#35 ) and another to store any ideas for tweaks (#36 ) so with that in mind: are you okay if I close this issue?
