### ISSUE TITLE
Draft Module 5: 'Inclusive Facilitation'

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#13]
## Summary

Need to create a strong draft of this module so that we can revise and eventually offer this section of the course. **This is Carrie Kappel**

## Sub-Tasks

- [x] Draft module skeleton
- [x] Draft learning objectives
    - Consider using a diversity of [Bloom's Revised Taxonomy](https://www.celt.iastate.edu/instructional-strategies/effective-teaching-practices/revised-blooms-taxonomy/) verbs
- [x] Draft content
    - Could include, text, code, slides, or some combination of those!
- [x] Identify companion readings / activities
    - For readings, may make sense to divide between readings for before and readings for after
- [x] Identify bonus resources
    - "Bonus" as in related but external resources that are not a required part of the module but might be useful for students interested in delving deeper
- [x] Gather feedback from SSECR design team
    - [x] Implement feedback

## Resources

- SSECR website [module page](https://lter.github.io/ssecr/mod_facilitation.html)
- "Draft Course Objectives" Google Doc
    - In Shared Drive for course

**Comment by ckappel** [comment]
Hi Nick, ready for content upload - available in this google doc: https://docs.google.com/document/d/1HVKy1vskLNxpDcLrBz-n5wO82Hbi0oXxshrW9OooF1M/edit?usp=sharing 

Thanks so much!
Carrie

**Comment by njlyon0** [comment]
## Update

Ported Carrie's Google Doc content (see above) into the website. Tried to adhere as much as possible to Carrie's style comments from the Google Doc though it is possible some errors occurred during the migration process.

**Comment by njlyon0** [comment]
## Teaching Issue Opened

For more details / a reminder on key teaching considerations for this module, see #37

**Comment by ckappel** [comment]
I tried to make some changes, editing directly in github, but I don't see them reflected on the website. Probably my error. Can you see whether you can see my changes on your end?

**Comment by marty-downs** [comment]
Comments:

- [ ] In "Moving from Debate to Dialogue" the last sentence starts "Both are critical to the collaborative process...". I'm not clear what "Both" refers to. Debate and Dialogue? Exploring complex issues and creating shared meaning?
- [ ] Also, the taxonomy is useful, but I'd love to see a few practices for helping move a conversation that is mired in debate toward one that is more skillful. I think people (me included) can often recognize when this happens, but lack good tools to address it.
- [ ] In the team planning activity, seems like deciding on which upcoming meeting they want to focus on should be the first item.
- [ ] Do we want to include any additional information/considerations for meeting online v. in person? (Since all their remaining meetings will be online.)

**Comment by ckappel** [comment]
@njlyon0 I'm very sorry for the super last minute request, but I have two figures that I would like to add to this module, based on Marty's request, and I don't know how to upload the pngs. Can you help? I've uploaded them here and I think I can write the code properly to have them show up where I want them. I just don't know how to get them in the image folder.

![figure_four-player-model](https://github.com/user-attachments/assets/d95af1ab-9371-4df4-b039-ebf922c8aa0c)
![figure_stuck-communication-patterns](https://github.com/user-attachments/assets/0a0bb05b-2160-40d1-b1e7-04c8048b216c)

**Comment by ckappel** [comment]
Please replace the second figure with this version

![figure_stuck-communication-patterns](https://github.com/user-attachments/assets/07b076af-040b-4ed8-87b3-02abf8ef0d80)

**Comment by ckappel** [comment]
Marty, per this comment:

> * [ ]  Do we want to include any additional information/considerations for meeting online v. in person? (Since all their remaining meetings will be online.)

I added another reference on online meetings, and plan to speak to specific tips / traps for the virtual setting as I teach the module. I've also a few more specific recommendations for virtual meetings in existing sections (e.g. roles, process design).

**Comment by njlyon0** [comment]
No apologies needed! I just fixed those images @ckappel 

For future reference I think there were two small issues at play:

1. I think you clicked "Create new file" rather than "Upload file" in the "Add file" menu (see the screencap below) so instead of adding the image you wanted you added a 1 byte file that had the right name but didn't actually include an image

<img width="1109" alt="Screenshot 2024-10-31 at 10 05 43 AM" src="https://github.com/user-attachments/assets/69668f42-2eb6-4f14-95d7-fd90893fd8fd">

2. This is more pernicious and I run into it all the time when adding alt text to HTML-style image tags. Essentially, including double quotes inside of the alt text breaks the HTML because the alt text ends at the start of the quotes and then the HTML doesn't know how to process the rest of the 'unquoted' content that remains.

For example:

                                                                                            v-alt text ends here from HTML's perspective
<img src="my_picture.png" alt="Photo of me doing a "peace sign" on vacation" />
                                                                                             ^-everything from here on is misinterpreted / breaks the image


Replace with single quotes fixes the issue:

                                                       v-start of alt text                                                 v-end of alt text
<img src="my_picture.png" alt="Photo of me doing a 'peace sign' on vacation" />
