### ISSUE TITLE
Draft Module 7: 'Project Management

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#16]
## Summary

Need to create a strong draft of this module so that we can revise and eventually offer this section of the course.

## Sub-Tasks

- [x] Draft module skeleton
- [x] Draft learning objectives
    - Consider using a diversity of [Bloom's Revised Taxonomy](https://www.celt.iastate.edu/instructional-strategies/effective-teaching-practices/revised-blooms-taxonomy/) verbs
- [x] Draft content
    - Could include, text, code, slides, or some combination of those!
- [x] Identify companion readings / activities
    - For readings, may make sense to divide between readings for before and readings for after
- [x] Identify bonus resources
    - "Bonus" as in related but external resources that are not a required part of the module but might be useful for students interested in delving deeper
- [x] Gather feedback from SSECR design team
    - [ ] Implement feedback

## Resources

- SSECR website [module page](https://lter.github.io/ssecr/mod_project-mgmt.html)
- "Draft Course Objectives" Google Doc
    - In Shared Drive for course
