### ISSUE TITLE
Present at NCEAS Roundtable

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#2]
## Summary

I (Nick) got invited to present at NCEAS' monthly roundtable and it seems like a perfect opportunity to talk about however much of the course we have fleshed out by then / generate excitement. We could also ask for feedback on something(s) if there are facets that are sufficiently refined for feedback to be valuable!

Note that if timing works we could ask Greg Maurer if he'd like us to put a plug for his ESA short course (similar foci to SSECR) in the roundtable presentation

### Scheduling

- April 4, 2024
- 3:30-4:30p PT / 6:30-7:30p ET
- Typically 45-50 min talk / remainder for Q&A
- Draft title: "Synthesis Skills for Early Career Researchers: A Project-Focused LTER Course"

## Sub-Tasks

- [x] Draft outline of presentation
- [x] Draft presentation content
- [x] Get feedback from Marty / SSECR team / LNO team
    - [x] Refine content
- [x] Get feedback again
    - [x] Further refine content
- [x] Give talk on 4/4/24

## Resources

- [SSECR](https://lter.github.io/ssecr/) Quarto website
- GitHub repository: [lter / ssecr](https://github.com/lter/ssecr)
- Presentation GitHub repository [njlyon0 / lyon_talks](https://github.com/njlyon0/lyon_talks)

**Comment by njlyon0** [comment]
## Update

- Presenting at next LNO team meeting (2/8) for internal feedback pre-roundtable

**Comment by njlyon0** [comment]
## Progress Report

I'm working hard to get a solid draft of the slides prepped before the team meeting so that I/we can get meaningful feedback from that conversation. Started a GitHub repository (under my GitHub because I'm not sure if the repo will have just SSECR talks or be more broad but I do feel confident they'll all be my talks) and the draft slides are deployed [here](https://njlyon0.github.io/lter_talks/slides/nceas_roundtable-4-24.html#/title-slide)

**Comment by njlyon0** [comment]
## Progress Report

Finished first draft of basically all slides! Still pretty rough in a lot of places so I need to do some smoothing/refining before getting another set of eyes on it for team review. That said, in a reasonably good place for review now (just not totally meeting my own standards of 'polished enough for others' as of right now.)

**Comment by njlyon0** [comment]
## LNO Team Feedback

- [ ] Say more about current working groups structure and products
    - Double benefit of internal promotion and make it more explicit how SSECR projects tie into working groups
- Need to consider what we “want” from the NCEAS people / how they can get involved
    - [ ] Lots of people would be potentially interested in being “inspiration speakers” (only prerequisite is they have some self-defined experience with synthesis)
    - [ ] For people with significant module experience with one module there is a small pool of money that we could use to engage them in module development
    - [ ] Could be cool to plan for a hackathon/code sprint in July where people could look at the finished modules and give feedback
    - [ ] We do have module flexibility at this point so we could ask people whether any modules are missing or are present and maybe should be
    - [ ] Suggestions for groups of learners to self-determine into project groups
- [ ] Slide 8: change “X” for “6 publications”
- [ ] Could embed image from the dashboard
- [ ] Make plan for following up via Slack with NCEAS community
    - [ ] What resources on these topics have you encountered?
    - Can them embed these resources into the website
- [ ] What resources would you find helpful to support struggling groups?
    - [ ] Add (more) info on “science mentors” for projects
    - Implicit safety net for groups that are struggling conceptually and/or having personality conflict issues
- [ ] Add information on course time commitment / stage of graduate student invited
    - Including this would clarify the sort of assumed background knowledge / prior experience

**Comment by njlyon0** [comment]
## Update - Added WG Examples

Fleshed out three slides giving examples of working group products / institutional diversity. Groups were recommended by Marty as valuable examples for various reasons.  

### General Status Update

Nearly done with a strong(er) draft of the entire slide deck! Just gotta finish refining the 'student project' section and we are good to go (for another round of feedback most likely).

**Comment by njlyon0** [comment]
## Refined Draft Completed

Finished my edits to the slide deck including implementing all LNO team feedback. Need another round of review but roundtable is not until April so I think this can safely be relegated to the back burner for a little bit

**Comment by njlyon0** [comment]
## Final Prep Stuff

Camila reached out to me and let me know that I need to provide an abstract for the talk and a short bio for myself. Should be easy enough to adapt from existing materials but still felt worth documenting here

**Comment by njlyon0** [comment]
## Presentation Given

Presentation given and feedback requested (via Slack). Already made note of / integrated the comments we got during the Q&A at the end of the roundtable so we can go ahead and close this issue here.
