### ISSUE TITLE
Present at LTER Community Call

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#21]
## Summary

Marty Downs and I are presenting at the March LTER Community Call. Fortunately, can adapt the NCEAS Roundtable slides to save a lot of shared preliminary work (see #2 ).

### Scheduling

- March 27, 2024
- 9-10a PT / 12-1p ET
- LTER [Community Call webpage](https://lternet.edu/stories/lter-community-calls/)

## Sub-Tasks

- [x] Duplicate roundtable slide deck as a starting point
- [x] Make Community Call-specific changes
    - [x] Change request for feedback to Discourse (instead of NCEAS Slack)
    - [x] Narrow invitation for collaboration (maybe?)
- [x] Get feedback from Marty / SSECR team / LNO team
    - [x] Refine content
- [x] Divvy up presentation components
    - Meeting scheduled on this purpose for 3/25
- [x] Give talk on 3/27/24

## Resources

- [SSECR](https://lter.github.io/ssecr/) Quarto website
- Presentation GitHub repository [njlyon0 / lyon_talks](https://github.com/njlyon0/lyon_talks)
    - Community Call [slide deck](https://njlyon0.github.io/lyon_talks/slides/lter-ssecr_community-call-2024.html#/title-slide)

**Comment by njlyon0** [comment]
## Meeting 3/25/24

Make the following edits:
- [ ] Add pronouns to LNO staff diagram
- [ ] "On the Horizon" slide edits
    - [ ] Change "soon" to "out"
    - [ ] Remove "by LNO staff"
    - [ ] 

### Presentation Roles

- LTER Network Background -- Marty
- Course Rationale 
    - Synthesis Research (7) - Silica Exports (14) -- Marty
    - ECRs (15-16) -- Nick
    - 17 - 18 -- Marty
- Course Structure & Content
    - SSECR Goals (19) -- Marty
    - Target Audience (20) -- Nick
- Student Projects -- Nick
- What’s Next -- Nick (with support from Marty)

**Comment by njlyon0** [comment]
## Edits Implemented

Made edits (to both this and Roundtable slide deck) as directed by Marty and it's looking like we're in a great place for Wednesday's community call!

I tracked down my custom LNO staff diagram powerpoint and put it in a more findable place in the Google Drive (`LTER-LNO-general / communications-products / 2024-lno-staff-diagram`) which should make it more easily editable going forward. Finally, I also added links to this / the roundtable slide deck to a new `ssecr-course` subfolder of the `presentations` folder in the same Shared Drive as the staff diagram.

**Comment by njlyon0** [comment]
## SSECR 3/26/24 Meeting

- Verbally emphasize and/or add a slide or two about how we intend to work with mentors
    - Matchmaking of teams with mentors based on discipline / interests
    - Substantial opportunities to connect with team mentors but also intermittent 
    - Professional networking built in

**Comment by njlyon0** [comment]
## Presentation Done!

Gave the presentation and it seemed like it went well! Posted a request for feedback on Discourse (see [here](https://lternet.discourse.group/t/synthesis-skills-for-early-career-researchers-ssecr-feedback/579)) so we'll see what sort of feedback comes in. That said, I think we can safely close this issue
