### ISSUE TITLE
Draft Bonus Module: 'Interactivity'

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#22]
## Summary

Need to create a strong draft of this module so that we can revise and eventually offer this section of the course.

## Sub-Tasks

- [x] Draft module skeleton
- [x] Draft learning objectives
    - Consider using a diversity of [Bloom's Revised Taxonomy](https://www.celt.iastate.edu/instructional-strategies/effective-teaching-practices/revised-blooms-taxonomy/) verbs
- [x] Draft content
    - Could include, text, code, slides, or some combination of those!
- ~~Identify companion readings / activities~~
- [x] Identify bonus resources
    - "Bonus" as in related but external resources that are not a required part of the module but might be useful for students interested in delving deeper
- [ ] Gather feedback from SSECR design team
    - [ ] Implement feedback

## Resources

- SSECR website [module page](https://lter.github.io/ssecr/mod_interactivity.html)

**Comment by njlyon0** [comment]
## Progress!

Made strong progress on this module. Completely drafted the 'fundamentals' topic as well as the first reactive app topic (may need a second one to demonstrate more nuance but the first is a nice '101-level' (I think/hope)

**Comment by njlyon0** [comment]
## Draft Content Completed

Finished the first draft of the content but still need to figure out reasonable activities / discussions. Note that facet of the module may be less (or more) important than in other modules because this module (and the spatial one) are "bonus" and likely won't be covered in class. May need to discuss with SSECR team to figure out where my dev time is best spent

**Comment by njlyon0** [comment]
## Activity Decision

This is a bonus module that either won't be synchronously taught or won't be until April/May 2025. Because of this, we're going to skip activities / discussions.
