### ISSUE TITLE
Teach: Version Control

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#26]
## Sub-Tasks

**Before**
- [x] Create Google Calendar event & Zoom room
- [x] Invite instructors & students to Calendar event
- [x] Make plan with co-instructors for dividing lesson
- [x] Make empty Google Doc for notes/questions

**During**
- [x] Start recording Zoom
- [x] Share link to Drive folder + notes Google Doc
    - Double check that everyone has access to both
- [x] Teach the module!

**After**
- [ ] Upload Zoom recording to Drive folder

## Resources

- Module [link](https://lter.github.io/ssecr/mod_version-control.html)
- Module [Drive folder](https://drive.google.com/drive/u/0/folders/1WTkI66erP4PoyuAAAQIlUt6S2V6R68x1) and [Notes document](https://docs.google.com/document/d/19vGEI8YZ779Q4gJdBvSk3CzzS0MOb6tdfXrLdhrC8JQ/edit#heading=h.9awpyspdaj01)

**Comment by njlyon0** [comment]
## Teaching Plan Drafted

Current plan for teaching this module is:

- Introductions & Course Welcome (15-30 min) -- Marty
- Share Key Links (5 min) -- Nick
    - Cohort-specific Drive folder ([2024-cohort](https://drive.google.com/drive/u/0/folders/1udGa9ncpAPOGxWw0ochssRcpOECMlC7T))
    - [Version Control Module Notes](https://docs.google.com/document/d/19vGEI8YZ779Q4gJdBvSk3CzzS0MOb6tdfXrLdhrC8JQ/edit#heading=h.9awpyspdaj01) Google Doc
    - Schedule/roster Google Sheet ([2024_schedule](https://docs.google.com/spreadsheets/d/1giaThq9QcngINHMvIBRCe-4DSf9ctaKxwgddewPkEbY/edit?gid=1857483727#gid=1857483727))
- Workflows (10-15 min) -- Nick
- Git & GitHub (45-60 min) -- Angel
    - Exercise: Create a repository
- Break (5-10 min)
- Git + RStudio (45-60 min) -- Nick
    - Exercise: Clone a repo + practice pushing & pulling

**Comment by njlyon0** [comment]
## Done!

Wow that module went great! Ton of good engagement and questions from the students and all-around good energy. Zoom is converting the meeting recording on my computer now but I'll upload that to the Drive as soon as it finishes
