### ISSUE TITLE
Add 'Quick Plots' to Data Visualization Module

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#29]
## Summary

Discussed as a group and decided we need a 'quick and dirty' graphing section in one of the modules. After some more chats it felt like the data viz module was the one where this belonged and Sarah is taking point on fleshing that bit out!

## Sub-Tasks

- [x] Sarah & Nick compare notes on framing of this topic
- [x] Sarah drafts topic
- [x] Nick reviews / gives feedback
- [x] Sarah cleans up narrative text
- [x] Sarah adds a few more post-harmonization examples
- [x] Nick ports to live website
- Future sub-tasks TBD

## Resources

- Data viz module (on GitHub): [here](https://github.com/lter/ssecr/blob/main/mod_data-viz.qmd)

**Comment by njlyon0** [comment]
## Update

Sarah drafted this topic in a Google Doc so the ball is in my court to review it!

**Comment by njlyon0** [comment]
## Draft Reviewed

Hey @scelmendorf ! I just looked over your [draft content]() and it looks great to me! I made some very minor tweaks to grammar and replaced the bit of the code that used the bang bang operator (`!!`) but otherwise I'd be happy for this variant of the materials to get integrated into the module!

Is there anything else you'd like feedback-wise before we roll this into the living website?

Also, I'm happy to either do that migration myself or leave it to you so just let me know what your preference is

**Comment by scelmendorf** [comment]
@njlyon0 Thanks for the review. Definitely yes to all your code tidying suggestions. If you think the basic content/framework seems right, I'll clean up and clarify the narrative text to sound less like stream-of-consciousness and more like teaching material. I'll also have a scan again of student projects and see if I can dig up some post-harmonization code that might be relevant to what they're working on for the bonus examples section. (pretty sure there were some taxonomy ones). My thoughts were viz for pub and viz for presentation could stay more or less as is, though we'll want to revisit at some point just to check on length/maybe do a run through and see how much we can fit in vs shift to bonus?

**Comment by njlyon0** [comment]
Sounds great and thanks for adjusting the sub-tasks at the top of the module!

Yeah, we can definitely do a run through of the content to get a sense for timing. I think also we'll probably need to at least informally survey students before offering the module because if most of them feel pretty solid on the fundamentals of `ggplot2` then we skip/reduce emphasis on that topic.

I was thinking we could spend like 30-45 minutes on this new data exploration content and its associated activity then take a break for 5-10 and then go into another 45 minutes or so on fundamentals of `ggplot2` and multi-panel graphs (putting emphasis on fundamentals to the extent is needed but otherwise focusing on faceting/plot grids). Then the module wraps up with a few nods at the other sections included in the end of the module but not actually covering them synchronously (I think it was cool/valuable to include those things in the module even though the plan is to not teach them during the instructional period)

Anyway do you want to just \@ me when you want me to port the content of that Google Doc over into the website?

**Comment by njlyon0** [comment]
## Feedback Request

Hey @gremau and @lkuiucsb , would you mind taking a look at the draft additional chunk of this module that Sarah's been working in and weighing in? We're thinking that the [current module](https://lter.github.io/ssecr/mod_data-viz.html) does 'nice graphs' relatively well but Sarah raised the point that we should start with 'quick and dirty' graphs then do 'nice graphs' and then probably include some toy example code for iterating across graphs.

Sarah's content lives in the Shared Drive as a Google Doc in the following path: `notes > module_notes > data_viz > Data Vis? Or Viz - rough outline`

**Comment by njlyon0** [comment]
## Content Ported to Website

First pass of integrating content from Sarah's Google Doc into the website. It renders / looks good to me but will pass it around to the team (esp. Sarah) to make sure it passes muster. Also added the prep code for the final 'bonus demo' to the `scripts/` folder but did not include it in the module (yet) because it doesn't run on my computer in its current form.

Also tried to integrate Li's/Greg's feedback where it wasn't superseded by our most recent design team meeting

**Comment by njlyon0** [comment]
## Done!

Finished adding the Google Doc content to the website. Marked the Google Doc clearly as deprecated so near future updates should be made directly in the website and/or tracked in a new location.

Closing this issue because we're re-opening #7 to track the home stretch of this module's development
