### ISSUE TITLE
Draft 'AI Statement' for Course Participants

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#3]
## Summary

"AI" (large language models) are increasingly popular / accessible and it is likely that students will encounter these tools during the course. Would be nice to have a syllabus-style paragraph or two outlining the LTER Network's thoughts/feelings in this arena. Broadly our thoughts (so far) are "use responsibly and be careful not to shortchange your own learning/skill acquisition"

## Sub-Tasks

- [x] Read more formal literature to get a sense for thinking in the field on this
- [x] Draft "policy"
- [ ] Ping Marty for review
    - [ ] Implement feedback
- [ ] Build into SSECR course website

## Resources

- Ray, 2023. [ChatGPT: A comprehensive review on background, applications, key challenges, bias, ethics, limitations and future scope](https://www.sciencedirect.com/science/article/pii/S266734522300024X)
- MEDS [Teach Me How to Google](https://ucsb-meds.github.io/teach-me-how-to-google/#1) slidedeck
    - Includes note on chatGPT at start of presentation

**Comment by njlyon0** [comment]
## First Draft Done

Made a first draft in [this Google Doc](https://docs.google.com/document/d/1EETjYN8ORgA5w0jMVp-ffr439s8s7eHrjsmHUlgjZlQ/edit) (in the `notes` folder of the SSECR Drive). Will add a request for review to the action items of our next meeting to--hopefully--get a finalized version of this embedded in the website ASAP.

**Comment by njlyon0** [comment]
## Done

Received and integrated feedback from Marty. Built content into course homepage by including embedding a separate Quarto doc (hopefully easier to maintain in future). See [Course Policies](https://lter.github.io/ssecr/#course-policies) header of home page of website
