### ISSUE TITLE
Draft Survey for Student Feedback on Content

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#34]
## Summary

The design team met and discussed the benefits of surveying students balanced against the risk of surveying them too much / losing quality of responses. We decided that we could survey at the end of each phase (~4 modules & ~ 2 months) and likely balance the risks and benefits of either approach. For a full set of that discussion see the 10//08/24 notes in the running notes doc for 2024

## Sub-Tasks

- [ ] Draft the 'post-phase I' survey
- [ ] Share with the design team & gather feedback
- [ ] Send the survey to the students!
- Further sub-tasks TBD

## Resources

- Survey content is in the Shared Drive in the top-level `assessment` folder

**Comment by njlyon0** [comment]
## First Draft Complete

Created a draft of the survey (see `assessment > 02_during-course > 2024_phase-1-survey` in the Shared Drive) that includes--I think--the main points we wanted to include. Need to share this across the design team to solicit feedback

**Comment by njlyon0** [comment]
## Emailed Design Team

Sent my draft via email to the design team and invited them to either email feedback to me or post it in this issue. We'll try to send out the survey ASAP after the team science module so that everyone's memory is still sharp

**Comment by ckappel** [comment]
- It might be helpful in the intro blurb to tell them that the survey asks for their input on three parts: content, instruction, and panels, so that they save their feedback for the appropriate section.
- I like how the instructors and panels sections have a header - can you add one for the Content section, too?
- Please add a Q for the panel for the Team Sciences Practices session in section 3

**Comment by scelmendorf** [comment]
I am in favor of short surveys (so make only the really fast things required, rest optional) and for only asking for actionable content. To that end I would:
- label all the free-form fields as optional and 
-  remove the 1-5 ratings on individual instructors on the logic that you probably don't have a roster of backup instructors you can sub in.
- if removing 1-5 on instructors, you could add these types of hints to the free-form anwers, e.g. "how can xxx improve their instructional approach for future cohorts?(e.g. communication, organization, speaking pace, etc.) Feel free to also use this space to comment on any elements you thought this instructor did really well!"

As always - these are just suggestions based on my personal tendencies which may not be representative. If a survey has a lot of required long form sections only some of which I have a strong opinion on, I usually ignore it.

**Comment by gremau** [comment]
Looks very good, but I agree with Sarah that the instruction section is perhaps more fine-grained than will be useful. It could be condensed in the way she suggests so that individual instructors can zero in and address feedback specifically directed at them. Plus, rankings with a range of 5 categories for speaking pace or organization may not be as interpretable as just counting up the number of responses that said "slow down" or provided organizational suggestions. Carrie's suggestion for a little outline in the introduction is also a good idea.

The third question is on ranking the interactivity, but also includes a sub-question on "was it useful to you?". Ranking interactivity gets at how engaging/effective the material is, but I think having students reflect on the usefulness of the material might warrant a separate question.

**Comment by njlyon0** [comment]
Added example/description text to all questions about module content (thanks for the rec Li!)

**Comment by njlyon0** [comment]
## Survey Sent

Survey shared with students so closing this issue. May open a new one for tweaks to the survey for the next batch of modules (a.k.a. "phase")
