### ISSUE TITLE
Improvements: Team Science Practices

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#36]
## Summary

Marty & Carrie are teaching this module on 10/17 (see #35 ) and creating this issue pre-emptively to store any ideas for improvement that come to mind.

## Sub-Tasks

- [ ] Standardize syntax for image embedding to HTML (some images are markdown)
- [ ] Add alt text to all images
- [ ] Standardize image file names to use prefix structure of other images & update in module
- [ ] Check / standardize 'additional resource' format and links

## Resources

- TBD

**Comment by njlyon0** [comment]
## Closing!

Any revisions not yet accomplished are obviated by course structure edits (see #67 )
