### ISSUE TITLE
Draft Module 1: 'Reproducibility Best Practices'

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#4]
## Summary

Time to get started actually developing course content! Need at least one fully-fleshed out module to share with external instructors developing their own modules (so they have a blueprint to compare their structure/content against). Will begin with 'reproducibility best practices' as this is the very first module.

## Sub-Tasks

- [x] Create a brief 'overview' description for this module
- [x] Revise/refine our draft learning objectives
- [x] Flesh out actual content of module
    - Could include, text, code, slides, or some combination of those!
- [x] Identify companion readings / activities
    - For readings, may make sense to divide between readings for before and readings for after
- [x] Identify bonus resources
    - "Bonus" as in related but external resources that are not a required part of the module but might be useful for students interested in delving deeper
- [x] Ping SSECR design team for review
- [x] Gather feedback
    - [x] Implement feedback

## Resources

- SSECR Reproducibility [module page](https://lter.github.io/ssecr/mod_reproducibility.html)
- "Draft Course Objectives" Google Doc
    - In Shared Drive for course

**Comment by njlyon0** [comment]
## Resources Added

Linked resources we had previously identified in the bottom of the module.

**Comment by njlyon0** [comment]
## Overview & Learning Objectives Drafted

Took a stab at these 'big picture' components of the module to help guide my thinking about the structure/content of the "meat" of the module. Going to take a small break from active coding and read some of the primary lit I've found thus far to make sure our content is all up to date with the latest of what actually constitutes "best practice".

**Comment by njlyon0** [comment]
## Progress Report

Drafted the 'FAIR and CARE' section of the module. Certainly needs another set of eyes/revision but will try to draft the entire module to maximize value of time spent by others reviewing/giving feedback.

**Comment by njlyon0** [comment]
## Draft 1 Content Complete

Finished the first--very rough--draft of the module content! It is _way_ too text heavy but I find it easier to remove detail while editing than add it in if it's not there in the first place. Also need to add more discussion prompts and activities but I figure that wasn't needed for this first, overly-detailed stab at the module.

**Comment by njlyon0** [comment]
## Note to Self

Change the commenting section to a tabset panel and split 'what' and 'why' between tabs

**Comment by njlyon0** [comment]
## Status Update

Making good progress refining the overly text-heavy draft into something a little more appealing / less dense. Including more visuals/simplifying text wherever possible. Working on a diagram variant of our suggested "reproducible project workflow" to embed in this lesson as a sort of visual overview of some of the fundamentals of this module.

Not totally happy with the draft as-is so not embedding in the module yet but I'm developing the figure through iterative revision in a PowerPoint file (see "ssecr-project-workflow.pptx" in the ["graphics" Shared Drive folder](https://drive.google.com/drive/u/0/folders/16wUc9DyJCrQc8I4idfTTImbRHN_y07Or))

**Comment by njlyon0** [comment]
## Refined Draft Complete

After a lot of refining / graphic creation and insertion I'm pretty pleased with the status of the Reproducibility module! Need to get some external eyes on it for sure but for an early draft I think this is much improved from my very first complete draft.

**Comment by njlyon0** [comment]
## Feedback Received

LNO team feedback was very useful! See team meeting notes for 4/16/2024

**Comment by njlyon0** [comment]
## Strong Draft Complete

Designing and refining these modules is an iterative process but at some point we do need to close issues to be able to prioritize less-developed content. Now that the LNO team has had a chance to weigh in I think we can safely call this module 'good enough' until we request larger course content review by the LTER / NCEAS community
