### ISSUE TITLE
Refine 'Multivariate Visualization' Bonus Module

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#41]
## Summary

The SSECR design team discussed the data viz module (in preparation to teach it for the 2024 cohort) and pointed out the 'ordination' is a very special case of visualization that might be better suited in a different module. So, I created a bonus 'multivariate visualization' module and bumped stuff there. This was a relatively coarse copy/paste approach so some refining is needed

## Sub-Tasks

- [x] Draft 'overview' of module
- [x] Revisit learning objectives  & draft new ones as needed
- [ ] Consider adding more multivariate methods
    - Chernoff faces? Star plots?
- [ ] Consider moving calculation of distance matrix to a different section of the module
    - This is a necessary step for many non-ordination methods too

## Resources

- TBD

**Comment by njlyon0** [comment]
## Done!

This bonus module was easy to make but didn't really get enough traction to be worth expanding in a big way right now. We may want some of these topics to get migrated to other sessions when we refactor the course module approach/order
