### ISSUE TITLE
Draft Module 2: 'Version Control'

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#5]
## Summary

This module is going to largely just point at the SciComp GitHub workshop (see link in 'Resources' section). So, it is the easiest module to create (arguably) though not representative of typical module structure or content. Still, just because it's low hanging fruit doesn't mean it's not worth doing

## Sub-Tasks

- [x] Create overview for module
- [x] Identify set of Bloom's taxonomy learning objectives
- [x] Embed SciComp materials in an accessible way
- [x] Link additional resources
- [ ] Ping SSECR design team for review
- [ ] Gather/implement feedback

## Resources

- SSECR Version Control [module page](https://lter.github.io/ssecr/mod_version-control.html)
- NCEAS SciComp Team [GitHub workshop website](https://nceas.github.io/scicomp-workshop-collaborative-coding/)

**Comment by njlyon0** [comment]
## First Draft Complete!

Finished the first pass at this module's page (it is likely to be the smallest/simplest module to design). Included a nifty HTML "iframe" which allows us to embed another website/HTML resource inside of the course website! The embedded site is fully navigable which could be a fun feature for this module even if ultimately we want students to enter the workshop website directly and work from there.

Need to get feedback from the group to create a revised second draft but this is not bad (in my opinion) for a first attempt.
