### ISSUE TITLE
Draft Module 3: 'Data Discovery & Management'

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#6]
## Summary

Need to create a strong draft of this module so that we can revise and eventually offer this section of the course.

## Sub-Tasks

- [x] Draft module skeleton
- [x] Draft learning objectives
    - Consider using a diversity of [Bloom's Revised Taxonomy](https://www.celt.iastate.edu/instructional-strategies/effective-teaching-practices/revised-blooms-taxonomy/) verbs
- [x] Draft content
    - Could include, text, code, slides, or some combination of those!
- [x] Identify companion readings / activities
    - For readings, may make sense to divide between readings for before and readings for after
- [x] Identify bonus resources
    - "Bonus" as in related but external resources that are not a required part of the module but might be useful for students interested in delving deeper
- [x] Gather feedback from SSECR design team
    - [x] Implement feedback

## Resources

- SSECR website [module page](https://lter.github.io/ssecr/mod_data-disc.html)
- "Draft Course Objectives" Google Doc
    - In Shared Drive for course

## Resources

- TBD

**Comment by njlyon0** [comment]
## Update

We've mostly been having this conversation during biweekly meetings over the last few months but good to summarize here for posterity. Essentially a small group of us (mostly Li/Greg/Nick) refined the learning objectives that we initially proposed and then Li drafted and revised corresponding module content which she is now in the process of finalizing so we can integrate it into the website!

The module is looking really cool so I think it'll be a treat to integrate it

**Comment by njlyon0** [comment]
## Update

Li asked me to migrate the content over and ping her if/when questions arise. I'll get going on that ASAP (likely tomorrow) and will post in the relevant Slack channel before I begin editing

**Comment by njlyon0** [comment]
## First Version is _LIVE!_

Just finished migrating Li's killer Google Doc over into the living website. Made some edits for clarity and some design choices that are only possible in the website format (i.e., tab panels) but the bulk of the content is consistent with the version in the now-superseded Google Doc.

**Comment by scelmendorf** [comment]
Very minor but suggestion but this blog: https://www.data-is-plural.com/ and the associated spreadsheet of cool datasets https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit?gid=0#gid=0  might be worth adding to the additional resources section. Not all ecology, some are may be pertinent to some projects (climate, ag, health) plus it's just cool to know what data are out there in the public domain.

**Comment by lkuiucsb** [comment]
Interesting blog!! I will add it to the resource part! Thanks Sarah!
Dr. Li Kui
Project Scientist
Marine Science Institute
Email: ***@***.***
[image: UC Santa Barbara]

**Comment by njlyon0** [comment]
## Done!

This module is live and reflects a _ton_ of work from the design team (most especially Li!). I've opened the 'actually teach the thing' issue (#31 ) so I think we can close this issue.

I've also opened an 'improvements' issue for this module so anything that comes to us in terms of edits we want to make after offering this module has a clear place for it to live
