### ISSUE TITLE
Draft Module 6: 'Data Visualization & Exploration'

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#7]
## Summary

Need to create a strong draft of this module so that we can revise and eventually offer this section of the course.

## Sub-Tasks

- [x] Draft module skeleton
- [x] Draft learning objectives
    - Consider using a diversity of [Bloom's Revised Taxonomy](https://www.celt.iastate.edu/instructional-strategies/effective-teaching-practices/revised-blooms-taxonomy/) verbs
- [x] Draft content
    - Could include, text, code, slides, or some combination of those!
- [x] Identify companion readings / activities
    - For readings, may make sense to divide between readings for before and readings for after
- [x] Identify bonus resources
    - "Bonus" as in related but external resources that are not a required part of the module but might be useful for students interested in delving deeper
- [x] Gather feedback from SSECR design team
    - [x] Implement feedback

## Resources

- SSECR website [module page](https://lter.github.io/ssecr/mod_data-viz.html)
- "Draft Course Objectives" Google Doc
    - In Shared Drive for course

## Resources

- TBD

**Comment by njlyon0** [comment]
## Self-Assigning

Assigning this to me (for now) so that we can begin drafting it ASAP

**Comment by njlyon0** [comment]
## First Draft Complete

Finished a first draft of this module. Need to go back through and refine and insert interactive bits (activities + discussions)

**Comment by njlyon0** [comment]
## Draft Done!

Finished my draft of ordination (metric and non-metric) and put in a pointer directing people to the spatial module if map-making is of interest. Closing this issue now but may open a related one when we revise / refine this module

**Comment by scelmendorf** [comment]
@njlyon0 adding things as I see them
- [ ] downlaod has a typo

**Comment by njlyon0** [comment]
## Code Demo Integrated

Just finished integrating the code demo into the end of the data viz module! Let me know what you think @scelmendorf !

I made two main changes that I'm happy to discuss:

1. Moved some contextual comments in code chunks into floating footnotes (little circles with a number on the line that show a comment when you hover over it)
2. Moved--most of--data prep to the [prep script](https://github.com/lter/ssecr/blob/main/scripts/prep-data_data-viz-demo.R) so code demo focuses primarily on visualization elements
    - Note though that I added several links / line references to that script in the code demo so that any interested parties _should_ be able to easily find and review the script to see how the data were wrangled / simulated

**Comment by scelmendorf** [comment]
@njlyon0 
- [ ] can you either add back in the mutate(plot = factor(class) so the withzeros data frame so the plot color aesthetic defaults to discrete color scale around here (or make the fake data have plots called plot_01...plot_10, then it will just read as a character vector so one doesn't have to mutate. Around here: https://github.com/lter/ssecr/blob/main/mod_data-viz.qmd#L673 
- [ ] Around here: https://github.com/lter/ssecr/blob/main/mod_data-viz.qmd#L687  change to geom_line as the connect the dots really helps spot the taxonomic errors in a way that the dots along don't
- [ ] Change  https://github.com/lter/ssecr/blob/main/mod_data-viz.qmd#L796 to "The first page of the resulting figure should look something like this:"

**Comment by njlyon0** [comment]
Ah, thanks for catching the `geom_line` thing. The prep code was superseded in a pernicious way so the desired error wasn't showing up so I switched to a scatterplot for debugging purposes and forgot to switch back

**Comment by njlyon0** [comment]
Okay, those changes are now rendering. the website should update itself in a minute or so but you may need to either close and re-open that tab or refresh the page to see the new changes

**Comment by scelmendorf** [comment]
@njlyon0 probably not worth risking breaking the build one hour before the class, but there is one tiny minor thing left in the checklist to do. It's a code comment in the bonus material, so deal with later just an FYI as i was clearly adding things to the list as you were ticking them off in our parallel efficiency bonanza yesterday.

**Comment by njlyon0** [comment]
I rolled the dice on rendering and was able to fix that typo without consequence; thanks for putting that on my radar!

**Comment by njlyon0** [comment]
## Closing!

Because we're teaching this in a little under an hour (see #39 ), I'm closing this issue. Ideas for improving/editing this module should be listed in #42 from here on out
