### ISSUE TITLE
Draft Module 9: 'Data Wrangling'

### ISSUE THREAD

**Issue by njlyon0** [lter/ssecr#8]
## Summary

Need to create a strong draft of this module so that we can revise and eventually offer this section of the course.

## Sub-Tasks

- [x] Draft module skeleton
- [x] Draft learning objectives
    - Consider using a diversity of [Bloom's Revised Taxonomy](https://www.celt.iastate.edu/instructional-strategies/effective-teaching-practices/revised-blooms-taxonomy/) verbs
- [x] Draft content
    - Could include, text, code, slides, or some combination of those!
- [x] Identify companion readings / activities
    - For readings, may make sense to divide between readings for before and readings for after
- [x] Identify bonus resources
    - "Bonus" as in related but external resources that are not a required part of the module but might be useful for students interested in delving deeper
- [ ] Gather feedback from SSECR design team
    - [ ] Implement feedback

## Resources

- SSECR website [module page](https://lter.github.io/ssecr/mod_wrangle.html)

**Comment by njlyon0** [comment]
## External Input Requested

I've drafted the high-level components that I think this module should likely include but I'm worried about under/over-estimating SSECR participants' prior knowledge. This module basically includes the bulk of what working groups ask me to do on a day-to-day basis so I worry that I have too little knowledge about what a "typical" ECR would have experienced outside of the course.

To that end, I've sent an email to a handful of ECRs involved in working groups / SPARC groups and asked them whether my current proposed list of topics is missing anything _or_ includes something it shouldn't. I'll summarize their responses here once I receive a plurality of them but in the meantime I'll put a pin in this module's development.

**Comment by njlyon0** [comment]
## Update

Fleshed out first bit of module (harmonizing, surface-level data exploration, QC intro) and have a good sense for the direction of the next bit of content

**Comment by njlyon0** [comment]
## Preliminary Activities/Discussions & Resources Added

Just like the header says, this module is looking pretty complete. The structure as of now is to cover 2-3 topics then do an activity or have a discussion to stop things from being too intense. Also added some bonus resources to this and other modules while I was making these edits

Next we need non-me eyes on this module to see how it "feels" to others and make any needed edits.

**Comment by njlyon0** [comment]
## Feedback Received

Angel Chen gave the following (super valuable) feedback on this module:

Harmonizing data

- “Users can generate this column key however they would like but” I feel like mentioning ltertools::begin_key() can be useful here?

Regular Expressions

- The 2nd page of posit’s [stringr cheatsheet](https://github.com/rstudio/cheatsheets/blob/main/strings.pdf) shows a pretty comprehensive list of regex options if that’s helpful to link as a resource?

Conditionals

- Code annotation to explain the first appearance of the piping operator?

Joining Data

- Typo in “Often the early steps of a synthesis project involve combine the data tables horizontally.”
- Add a short code annotation for this line to explain the regex?  dplyr::mutate(species = gsub(pattern = "^eel$", replacement = "moray eel", x = species))

Loops

- Code annotation for this line of purrr? purrr::list_rbind(x = crab_list)

Custom Functions

- Typo in “When writing your own functions is can also be useful to program defensively.”
- overall, great job trying to cover all the core topics in data harmonization/wrangling! this module strikes me as the perfect module for intermediate R users who are also somewhat already familiar with the tidyverse

**Comment by njlyon0** [comment]
## Angel Feedback Integrated

Like the title says, finished making all changes Angel suggested. Putting this back into 'pending external' until I can run it by the larger LNO team (hopefully in the near future)

**Comment by njlyon0** [comment]
## Closing!

To help triage the remaining tasks we'll be closing these 'draft module X' issues. Refinement of existing materials can warrant its own issue down the line (and may actually make gathering feedback from many sources easier)

**Comment by scelmendorf** [comment]
Few additional thoughts in wrangling now that it is in the 'what is wrangling/vis/harmonization' debate:
1. Resources to consider adding Rmonize package: https://cran.r-project.org/web/packages/Rmonize/vignettes/b-Data-processing-elements.html
1. Recent publication https://www.nature.com/articles/s41597-024-02956-3
1. Consider broadening the definition of harmonization from what's currently in the course using some definitions from the above paper. I think most would consider it to be more than renaming variables and formats
